# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TodoSwift' do
    use_frameworks!
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Alamofire'

    target 'TodoSwiftTests' do
        inherit! :search_paths
        # Pods for testing
    end

end
