# Uncomment the next line to define a global platform for your project
platform :osx, '10.13'

target 'DragMacApp' do
  use_frameworks!

    pod 'AFNetworking'
    pod "Qiniu"
    pod "CryptoSwift"
    pod "SwiftyJSON"
    pod "PromiseKit"

end
