# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'ReactSwift' do
use_frameworks!


pod 'ReactiveSwift', '~> 3.0'

pod 'RxSwift',    '~> 4.0'
pod 'RxCocoa',    '~> 4.0'
pod 'RxOptional'
pod 'NSObject+Rx'
pod 'RxDataSources', '~> 3.0'



pod 'PromiseKit'

pod 'ObjectMapper'


pod 'RxAlamofire'
pod 'Alamofire', '~> 4.5'
pod 'SwiftyJSON'


target 'ReactSwiftTests' do
    #inherit! :search_paths
pod 'RxBlocking', '~> 4.0'
pod 'RxTest',     '~> 4.0'
end

target 'ReactSwiftUITests' do
    #inherit! :search_paths
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            configuration.build_settings['SWIFT_VERSION'] = "4.0"
        end
    end
end


end

